library(readr)
library(igraph)
library(CINNA)

#Importing the asker-answerer file generated by python code
ask_ans <- read_delim("C:/Users/Ravali/Desktop/asker-answerer.tsv", 
                      "\t", escape_double = FALSE, trim_ws = TRUE)
col1<-ask_ans[1];
col2<-ask_ans[2];
#Data frame is created (Link) having two coloumns askerid and answerer id
link<-data.frame(
  asker=col1,
  answerer=col2)

#graph is assigned to varible 'net' which is directed
net<-graph_from_data_frame(d=link, directed=T)
#plot is drawn for net
plot(net,vertex.size = 3,vertex.color = 'red',edge.width = .1,
     edge.color = 'black',edge.arrow.size=.1, vertex.label = NA)

#gaint component is extracted from the existing graph
gaint<-giant_component_extract(net,directed = TRUE)

ask<-gaint[2][[1]][,1]
ans<-gaint[2][[1]][,2]
#gaint data is collected and formed a dataframe called 'link_big'
link_big<-data.frame(
  asker=gaint[2][[1]][,1],
  answer=gaint[2][[1]][,2]
)
#link_big is assigned to net1 which is directed graph
net1<-graph_from_data_frame(d=link_big, directed=T)
#Plot is done by using layout.fruchterman.reingold
plot(net1,vertex.size = 10,vertex.color= 'red',edge.width = .6,edge.color = 'black',
     edge.arrow.size=.2, vertex.label = NA,layout = layout.fruchterman.reingold)
#Output file is generated in .tsv format for link_big
write.table(link_big, file='giant_component.tsv', quote=FALSE, sep='\t', col.names = NA)
